"""add employee_meetings table

Revision ID: 9c784673d70e
Revises: d072262d8dd9
Create Date: 2025-03-27 08:59:34.868217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c784673d70e'
down_revision = 'd072262d8dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_meetings',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('meetings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employees_meetings_employee_id_employees')),
    sa.ForeignKeyConstraint(['meetings_id'], ['meetings.id'], name=op.f('fk_employees_meetings_meetings_id_meetings')),
    sa.PrimaryKeyConstraint('employee_id', 'meetings_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_meetings')
    # ### end Alembic commands ###
